export const ENDPOINTS = {
  LOGIN: "/accounts/auth/token/",
  FIND_ME: "/accounts/profile/",
  APARTMENTS_FIND_ALL: "/accounts/apartments/",
  APARTMENTS_FIND_BY_ID: (id: string) => `/accounts/apartments/${id}/`,
  CITIZENS_FIND_ALL: "/accounts/citizns/",
  CITIZENS_FIND_BY_ID: (id: string) => `/accounts/citizns/${id}`,
  SERVICES_FIND_ALL: "/accounts/services/",
  SERVICES_LIST: "/accounts/services/",
  SERVICES_CREATE: "/accounts/services/",
  SERVICES_READ: (id: string) => `/accounts/services/${id}/`,
  SERVICES_UPDATE: (id: string) => `/accounts/services/${id}/`,
  SERVICES_PARTIAL_UPDATE: (id: string) => `/accounts/services/${id}/`,
  SERVICES_DELETE: (id: string) => `/accounts/services/${id}/`,
  VILLAGES_FIND_ALL: "/accounts/villages/",
};
